### ISSUE TITLE
multilanguagecontainerizednamevalues update api changes text state incorrectly

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapi-bugs#2]
multilanguagecontainerizednamevalues update api changes the text state for a text holder even if its source text (name and value) are not changed.

The text state should be  updated only if the source text is changed.

![image](https://user-images.githubusercontent.com/13166236/77125039-dd633780-6a01-11ea-8578-68f1b4ed4ce4.png)

**Comment by perpetualintelligence** [comment]
Issue identifierd with multilanguagecontainerizednamevalues. IEquatable was not correctly implemented. Fixed the issue in v1...
