### ISSUE TITLE
Support export to XLIFF standard

### ISSUE THREAD

**Issue by VedantSahadeo** [perpetualintelligence/pidotapi-bugs#7]
Currently the Multilanguage API export supports CSV and TMX files. What is the plan for supporting export to XLIFF standard file?

![image](https://user-images.githubusercontent.com/62402148/80299921-e2956e00-8787-11ea-9ecb-46a12655b9bb.png)

**Comment by perpetualintelligence** [comment]
@VedantSahadeo thanks for reporting the issue. Support for XLIFF standard is in our release plan for v1 may 2020.

**Comment by perpetualintelligence** [comment]
Based on customer feedback prioritized the XLIFF export support to v1 apr 2020. Note this does not include the import.

**Comment by perpetualintelligence** [comment]
Export to XLIFF is now available for beta...

**Comment by perpetualintelligence** [comment]
![image](https://user-images.githubusercontent.com/62374075/81652787-21aefa80-93e9-11ea-871b-25432c165a1b.png)
